// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa_rVvyLJwOtCiuwHklpJGD4WD41JKPzU',
    appId: '1:803921875296:web:3019bf26430f27891f8e05',
    messagingSenderId: '803921875296',
    projectId: 'capstone-design-1-5235f',
    authDomain: 'capstone-design-1-5235f.firebaseapp.com',
    storageBucket: 'capstone-design-1-5235f.firebasestorage.app',
    measurementId: 'G-VHWYC8GT66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGdZTgCKZ-3YZnUAqsOca3axNV6GgyBJQ',
    appId: '1:803921875296:android:bc6b1e2745997bd61f8e05',
    messagingSenderId: '803921875296',
    projectId: 'capstone-design-1-5235f',
    storageBucket: 'capstone-design-1-5235f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa_rVvyLJwOtCiuwHklpJGD4WD41JKPzU',
    appId: '1:803921875296:web:bea60b9aabd19fdf1f8e05',
    messagingSenderId: '803921875296',
    projectId: 'capstone-design-1-5235f',
    authDomain: 'capstone-design-1-5235f.firebaseapp.com',
    storageBucket: 'capstone-design-1-5235f.firebasestorage.app',
    measurementId: 'G-WSLJ5PHZBQ',
  );
}
